### PR TITLE
Dispatch information while loading the user

### PR DESCRIPTION
**Pull request by rmkpatchaa**
This PR is intended to correct the behavior described in #76 .

### CODE REVIEW

**Comment by Tankanow** [comment]
Hi @rmkpatchaa, I also needed to fix this in my own code. I think you should use the existing `USER_NOT_FOUND` constant instead of creating the new  `LOADING_USER_END` because if the code gets to proposed line 26 in `loadUser`, this really means that the `oidc-client-js` returned successfully and did not find a user.

**Comment by rmkpatchaa** [comment]
Hi @Tankanow I've created the new **`LOADING_USER_END`** constant because it could be dispatched in many other cases (like a try, catch, finally -> LOADING_USER_END).
At this time we have only one case but we give also the possibility to someone to listen on the **`LOADING_USER_END`** action in his redux app.

**Comment by Tankanow** [comment]
Note that the `USER_NOT_FOUND` constant exists in the reducers already, but is missing from `constants/index.js`. The reducers can handle `USER_NOT_FOUND` the same way they handle `USER_FOUND`.

**Comment by Tankanow** [comment]
@rmkpatchaa you're proposed code does not dispatch LOADING_USER_END on USER_FOUND! I think `USER_FOUND` is a `LOADING_USER_END` event. To me, "loading user end" means either `USER_FOUND`, `USER_LOADING_ERROR`, or `USER_NOT_FOUND`.

**Comment by rmkpatchaa** [comment]
Hi @Tankanow this makes sense. I've update the code to use the user_not_found action instead.

**Comment by Tankanow** [comment]
@rmkpatchaa, thank you for submitting this patch! I appreciate that you were open to my comments. Looking forward to getting this code in my app once it's merged!

Cheers!

**Comment by rmkpatchaa** [comment]
@Tankanow you're welcome. The purpose was the same. Not the implementation. And I did it quickly to correct the behavior I had and did not take the time to think about other possibilities.
I hope it will be merged soon.

**Comment by maxmantz** [comment]
I have merged this manually, but without the `LOADING_USER_END` action. I hope this helps. Thank you for the PR.

**Comment by rmkpatchaa** [comment]
Hi @maxmantz I think it should do the job. I'll test it later on my project.

Cheers.

**Comment by killthrush** [comment]
@Tankanow  @maxmantz @rmkpatchaa - thanks!  Confirmed that in 3.0.0-beta.14 that the issue is resolved.  Also confirmed resolved: https://github.com/maxmantz/redux-oidc/pull/69.

**Pull request closed without merging**
